//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiztechDashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiztechDashboardContext : DbContext
    {
        public BiztechDashboardContext()
            : base("name=BiztechDashboardContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WDSB_BUContacts> WDSB_BUContacts { get; set; }
        public virtual DbSet<WDSB_BusinessUnits> WDSB_BusinessUnits { get; set; }
        public virtual DbSet<WDSB_Comments> WDSB_Comments { get; set; }
        public virtual DbSet<WDSB_Favorites> WDSB_Favorites { get; set; }
        public virtual DbSet<WDSB_Features> WDSB_Features { get; set; }
        public virtual DbSet<WDSB_Applications> WDSB_Applications { get; set; }
        public virtual DbSet<WDSB_Projects> WDSB_Projects { get; set; }
        public virtual DbSet<WDSB_TempProjects> WDSB_TempProjects { get; set; }
        public virtual DbSet<VW_WDSB_GetNewApp> VW_WDSB_GetNewApp { get; set; }
        public virtual DbSet<WDSB_AppUsers> WDSB_AppUsers { get; set; }
    }
}
