//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiztechDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_WDSB_GetNewApp
    {
        public string ProjectID { get; set; }
        public string AppName { get; set; }
        public Nullable<bool> AppIsActive { get; set; }
        public string AppDatasource { get; set; }
        public string AppDatabaseName { get; set; }
        public string AppUserID { get; set; }
        public string AppPassword { get; set; }
    }
}
