//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiztechDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_WDSB_GetNewApp
    {
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDatasource { get; set; }
        public string ProjectDatabaseName { get; set; }
        public string ProjectUserID { get; set; }
        public string ProjectPassword { get; set; }
        public Nullable<bool> ProjectIsActive { get; set; }
        public string FrontEndPath { get; set; }
        public string BackEndPath { get; set; }
    }
}
