//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiztechDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WDSB_Comments
    {
        public int CommentID { get; set; }
        public int AppID { get; set; }
        public string Comment { get; set; }
        public string UserName { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string Subject { get; set; }
    
        public virtual WDSB_Applications WDSB_Applications { get; set; }
    }
}
