//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiztechDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WDSB_VW_ApplicationsDB
    {
        public int AppID { get; set; }
        public Nullable<bool> AppIsWeb { get; set; }
        public string BUName { get; set; }
        public string DevFront1 { get; set; }
        public string DevBack1 { get; set; }
        public string DevFront2 { get; set; }
        public string DevBack2 { get; set; }
        public string DevFront3 { get; set; }
        public string DevBack3 { get; set; }
        public string AppName { get; set; }
    }
}
