//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiztechDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WDSB_VW_ApplicationsDB
    {
        public int AppID { get; set; }
        public string AppName { get; set; }
        public Nullable<bool> AppIsWeb { get; set; }
        public string BUName { get; set; }
        public string DevFront { get; set; }
        public string ModFront { get; set; }
        public string OpsFront { get; set; }
        public Nullable<bool> IsUatAvail { get; set; }
        public Nullable<bool> AppIsActive { get; set; }
        public string ProjectOpsID { get; set; }
    }
}
