//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiztechDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WDSB_Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WDSB_Projects()
        {
            this.WDSB_AppUsers = new HashSet<WDSB_AppUsers>();
        }
    
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDatasource { get; set; }
        public string ProjectDatabaseName { get; set; }
        public string ProjectUserID { get; set; }
        public string ProjectPassword { get; set; }
        public Nullable<bool> ProjectIsActive { get; set; }
        public string FrontEndPath { get; set; }
        public string BackEndPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WDSB_AppUsers> WDSB_AppUsers { get; set; }
    }
}
