//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiztechDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WDSB_Applications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WDSB_Applications()
        {
            this.WDSB_Comments = new HashSet<WDSB_Comments>();
            this.WDSB_Favorites = new HashSet<WDSB_Favorites>();
            this.WDSB_Features = new HashSet<WDSB_Features>();
        }
    
        public int AppID { get; set; }
        public string AppName { get; set; }
        public int AppBU { get; set; }
        public string FrontTechnology { get; set; }
        public string BackTechnology { get; set; }
        public Nullable<int> AppLifespan { get; set; }
        public int PrimaryBUContact { get; set; }
        public Nullable<int> SecondaryBUContact { get; set; }
        public Nullable<bool> AppIsActive { get; set; }
        public Nullable<bool> AppPII { get; set; }
        public string AppSecurity { get; set; }
        public Nullable<System.DateTime> DateImplemented { get; set; }
        public Nullable<System.DateTime> LastProdDate { get; set; }
        public string AppVersion { get; set; }
        public string AppDesc { get; set; }
        public Nullable<bool> AppIsWeb { get; set; }
        public string ProjectDevID { get; set; }
        public string ProjectModID { get; set; }
        public string ProjectOpsID { get; set; }
        public string AppIconPath { get; set; }
        public Nullable<bool> IsUatAvail { get; set; }
    
        public virtual WDSB_BUContacts WDSB_BUContacts { get; set; }
        public virtual WDSB_BUContacts WDSB_BUContacts1 { get; set; }
        public virtual WDSB_BusinessUnits WDSB_BusinessUnits { get; set; }
        public virtual WDSB_Projects WDSB_Projects { get; set; }
        public virtual WDSB_Projects WDSB_Projects1 { get; set; }
        public virtual WDSB_Projects WDSB_Projects2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WDSB_Comments> WDSB_Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WDSB_Favorites> WDSB_Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WDSB_Features> WDSB_Features { get; set; }
    }
}
